CREATE USER POKE_STORE IDENTIFIED BY oracle;
GRANT CONNECT TO POKE_STORE;
GRANT CONNECT, RESOURCE, DBA TO POKE_STORE;
GRANT CREATE SESSION TO POKE_STORE;
GRANT DBA TO POKE_STORE;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to POKE_STORE;
GRANT UNLIMITED TABLESPACE TO POKE_STORE;
GRANT CREATE MATERIALIZED VIEW TO POKE_STORE;
GRANT CREATE TABLE TO POKE_STORE;
GRANT GLOBAL QUERY REWRITE TO POKE_STORE;
GRANT SELECT ANY TABLE TO POKE_STORE;

--CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES BAIRRO (ID_BAIRRO, ID_CIDADE)--

CREATE TABLE POKE_STORE.CLIENTE(
ID_CLIENTE VARCHAR2(500) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PIX VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
NOME VARCHAR2(255) NOT NULL,
ENDERECO VARCHAR2(255) NOT NULL,
CIDADE VARCHAR2(255) NOT NULL,
ESTADO VARCHAR2(50) NOT NULL,
TELEFONE CHAR(12) NOT NULL,
ID_PRODUTO INT(11) NOT NULL,
PRIMARY KEY (ID_CLIENTE),
CONSTRAINT FK_CLIENTE_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO),
CONSTRAINT FK_CLIENTE_CARRINHO FOREIGN KEY (ID_PRODUTO, ID_CARRINHO) REFERENCES CARRINHO (ID_PRODUTO,ID_CARRINHO)
);

CREATE TABLE POKE_STORE.PRODUTO(
ID_PRODUTO INT(11) NOT NULL,
NOME VARCHAR2(255) NOT NULL,
ID NUMBER NOT NULL,
QUANTIDADE NUMBER NOT NULL,
TIPO CHAR(1) NOT NULL,
VALOR NUMBER NOT NULL,
DESCRICAO VARCHAR2(255) NOT NULL,
PRIMARY KEY (ID_PRODUTO)
CONSTRAINT FK_PRODUTO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
CONSTRAINT FK_PRODUTO_CARRINHO FOREIGN KEY (ID_CARRINHO) REFERENCES CARRINHO (ID_CARRINHO)
);

CREATE TABLE POKE_STORE.CUPOM(
ID_CUPOM INT(11) NOT NULL;
DESCONTO NUMBER NOT NULL;
VALIDADE CHAR(4) NOT NULL;
PRIMARY KEY(ID_CUPOM)
CONSTRAINT FK_CUPOM_CARRINHO FOREIGN KEY (ID_CARRINHO) REFERENCES CARRINHO (ID_CARRINHO)
);

CREATE TABLE POKE_STORE.CARRINHO(
ID_CARRINHO INT (11) NOT NULL,
ID_CUPOM INT(11) NOT NULL,
ID_PRODUTO INT(11) NOT NULL,
PRIMARY KEY(ID_CARRINHO),
CONSTRAINT FK_CARRINHO_CUPOM FOREIGN KEY (ID_CUPOM) REFERENCES CUPOM (ID_CUPOM),
CONSTRAINT FK_CARRINHO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO),
CONSTRAINT FK_CARRINHO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
);
