CREATE SEQUENCE POKE_STORE.SEQ_USUARIO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE POKE_STORE.SEQ_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE POKE_STORE.SEQ_PRODUTO_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE POKE_STORE.SEQ_PRODUTO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


CREATE SEQUENCE POKE_STORE.SEQ_CUPOM
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

-- USUARIO --

INSERT INTO POKE_STORE.USUARIO (ID_USUARIO,PIX,EMAIL,SENHA,NOME,ENDERECO,CPF,CIDADE,ESTADO,TELEFONE ,DELETADO  )
VALUES (POKE_STORE.SEQ_USUARIO.nextval, 'antoniogomes@hotmail.com', 'antoniogomes@hotmail.com', 'antonio', 'ANTONIO GOMES', 'RUA UM', '03132190341','PORTO ALEGRE','RIO GRANDE DO SUL','51991458796', 'F');

INSERT INTO POKE_STORE.USUARIO (ID_USUARIO,PIX,EMAIL,SENHA,NOME,ENDERECO,CPF,CIDADE,ESTADO,TELEFONE, DELETADO)
VALUES (POKE_STORE.SEQ_USUARIO.nextval, 'joaokleber@hotmail.com', 'joaokleber@hotmail.com', 'kleber', 'JOAO KLEBER', 'RUA DOIS', '03216549875','PORTO ALEGRE','RIO GRANDE DO SUL','51987654321', 'F');

INSERT INTO POKE_STORE.USUARIO (ID_USUARIO,PIX,EMAIL,SENHA,NOME,ENDERECO,CPF,CIDADE,ESTADO,TELEFONE, DELETADO)
VALUES (POKE_STORE.SEQ_USUARIO.nextval, 'richarlison@hotmail.com', 'richarlison@hotmail.com', 'richarlison', 'RICHARLISON DE ALMEIDA', 'RUA TRES', '01154987652','PORTO ALEGRE','RIO GRANDE DO SUL','5199145876', 'F');

INSERT INTO POKE_STORE.USUARIO (ID_USUARIO,PIX,EMAIL,SENHA,NOME,ENDERECO,CPF,CIDADE,ESTADO,TELEFONE, DELETADO)
VALUES (POKE_STORE.SEQ_USUARIO.nextval, 'vladimir@hotmail.com', 'vladimir@hotmail.com', 'vladimir', 'VLADIMIR PUTIN', 'RUA DEZENOVE', '03132626987','PORTO ALEGRE','RIO GRANDE DO SUL','51974458796','F');

INSERT INTO POKE_STORE.USUARIO (ID_USUARIO,PIX,EMAIL,SENHA,NOME,ENDERECO,CPF,CIDADE,ESTADO,TELEFONE, DELETADO)
VALUES (POKE_STORE.SEQ_USUARIO.nextval, 'neyney@hotmail.com', 'neyney@hotmail.com', 'neyney', 'NEYMAR JR', 'RUA DEZ', '12345678911','SANTOS','SAO PAULO','51991458555','F');

-- PRODUTOS --

INSERT INTO POKE_STORE.PRODUTO (ID_PRODUTO,NOME,DESCRICAO,QUANTIDADE,TIPO,VALOR,ID_USUARIO, DELETADO)
VALUES (POKE_STORE.SEQ_PRODUTO.nextval,'Pikachu','Pelucia gigante de 1 metro e meio de altura',10,3,50.99,1,'F');

INSERT INTO POKE_STORE.PRODUTO (ID_PRODUTO,NOME,DESCRICAO,QUANTIDADE,TIPO,VALOR,ID_USUARIO,DELETADO)
VALUES (POKE_STORE.SEQ_PRODUTO.nextval,'Charizard','Pelucia gigante de 1 metro e meio de altura',80,3,67.99,2,'F');

INSERT INTO POKE_STORE.PRODUTO (ID_PRODUTO,NOME,DESCRICAO,QUANTIDADE,TIPO,VALOR,ID_USUARIO,DELETADO)
VALUES (POKE_STORE.SEQ_PRODUTO.nextval,'Pokemon Fire Red','Jogo de GBA EDICAO LIMITADA',100,1,3500.99,3,'F');

INSERT INTO POKE_STORE.PRODUTO (ID_PRODUTO,NOME,DESCRICAO,QUANTIDADE,TIPO,VALOR,ID_USUARIO,DELETADO)
VALUES (POKE_STORE.SEQ_PRODUTO.nextval,'Pokemon leaf Green','Jogo de GBA EDICAO LIMITADA',100,1,9500.99,4,'F');

INSERT INTO POKE_STORE.PRODUTO (ID_PRODUTO,NOME,DESCRICAO,QUANTIDADE,TIPO,VALOR,ID_USUARIO,DELETADO)
VALUES (POKE_STORE.SEQ_PRODUTO.nextval,'Nintendo Switch','Edicao Deluxe Ouro Macico',3,2,11999.99,5,'F');

-- CUPOM ---

INSERT INTO POKE_STORE.CUPOM (ID_CUPOM, DESCONTO, DELETADO)
VALUES (POKE_STORE.SEQ_CUPOM.nextval, 150.00, 'F');

INSERT INTO POKE_STORE.CUPOM (ID_CUPOM, DESCONTO, DELETADO)
VALUES (POKE_STORE.SEQ_CUPOM.nextval, 200.00, 'F');

INSERT INTO POKE_STORE.CUPOM (ID_CUPOM, DESCONTO, DELETADO)
VALUES (POKE_STORE.SEQ_CUPOM.nextval, 190.00, 'F');

INSERT INTO POKE_STORE.CUPOM (ID_CUPOM, DESCONTO, DELETADO)
VALUES (POKE_STORE.SEQ_CUPOM.nextval, 80.00, 'F');

INSERT INTO POKE_STORE.CUPOM (ID_CUPOM, DESCONTO, DELETADO)
VALUES (POKE_STORE.SEQ_CUPOM.nextval, 80.00, 'F');

-- PEDIDOS (O VALOR FINAL TA ERRADO, PORQUE A GENTE NAO SABE COMO REFERENCIAR AO VALOR DO PRODUTO, AFINAL, O CLIENTE TERIA QUE ESCOLHER NO PEDIDO E SERIA BASEADO NA QUANTIDADE * PRECO - CUPOM) ----

INSERT INTO POKE_STORE.PEDIDO (ID_PEDIDO,ID_CUPOM,ID_USUARIO,VALOR_FINAL,DELETADO)
VALUES (POKE_STORE.SEQ_PEDIDO.nextval, 1, 1, 1230.00, 'F');

INSERT INTO POKE_STORE.PEDIDO (ID_PEDIDO,ID_CUPOM,ID_USUARIO,VALOR_FINAL,DELETADO)
VALUES (POKE_STORE.SEQ_PEDIDO.nextval, 2, 2, 120.00, 'F');

INSERT INTO POKE_STORE.PEDIDO (ID_PEDIDO,ID_CUPOM,ID_USUARIO,VALOR_FINAL, DELETADO)
VALUES (POKE_STORE.SEQ_PEDIDO.nextval, 3, 3, 930.00, 'F');

INSERT INTO POKE_STORE.PEDIDO (ID_PEDIDO,ID_CUPOM,ID_USUARIO,VALOR_FINAL, DELETADO)
VALUES (POKE_STORE.SEQ_PEDIDO.nextval, 4, 4, 960.00, 'F');

INSERT INTO POKE_STORE.PEDIDO (ID_PEDIDO,ID_CUPOM,ID_USUARIO,VALOR_FINAL, DELETADO)
VALUES (POKE_STORE.SEQ_PEDIDO.nextval, 4, 4, 1230.00, 'F');